directory-war/src/main/java/org/jbalance/directory/ui/beans/juridicals/KladrPanelHelper.java
package org.jbalance.directory.ui.beans.juridicals;

import java.util.Collections;
import java.util.List;
import java.util.Set;

import javax.validation.ConstraintViolation;
import javax.validation.Validation;
import javax.validation.Validator;
import javax.validation.ValidatorFactory;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotBlank;
import org.jbalance.directory.core.model.address.*;
import org.jbalance.directory.core.session.address.IAddressFinder;
import org.jbalance.directory.core.util.Log;
import org.jbalance.directory.core.util.Str;

public class KladrPanelHelper {

    protected Log log = new Log(getClass());
    private final IAddressFinder addressFinder;

    private static final String DELIMITER = ", ";
    private static final String DEFAULT_COUNTRY = "Российская Федерация";

    private String country = DEFAULT_COUNTRY;
    private String regionName;

    private List<Region> regionSugessionList;
    private List<City> citySugessionList;
    private List<Street> streetSugessionList;
    private List<House> houseSugessionList;

//	Selected objects
    /**
     * Индекс
     */
    private String zipCode;
    private IRegion region;
    private ICity city;
    private IStreet street;
    private IHouse house;
    /**
     * Квартира
     */
    private String apartments;
    /**
     * Является ли адрес абонентским ящиком?
     */
    private boolean isPostOfficeBox = false;
    private String postOfficeBox;

//	Following fields for search
    private String regionNamePrefix;
    private String cityNamePrefix;
    private String streetNamePrefix;
    private String houseNamePrefix;

    private final KladrListener listener;

    public KladrPanelHelper(IAddressFinder addressFinder, KladrListener listener) {
        super();
        if (listener == null) {
            throw new NullPointerException();
        }
        this.listener = listener;
        this.addressFinder = addressFinder;
        addressFinder.setLimitSelectCity(15);
        addressFinder.setLimitSelectStreet(15);

    }

    private boolean validate() {
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        Validator validator = factory.getValidator();
        Set<ConstraintViolation<KladrPanelHelper>> constraintViolations = validator.validate(this);
        for (ConstraintViolation<KladrPanelHelper> constraintViolation : constraintViolations) {
            log.warn(constraintViolation + "");
        }

        if (isPostOfficeBox) {
            if (Str.empty(postOfficeBox)) {
                log.warn("Заполните номер абонентского ящика!");
            }
        }

        return constraintViolations.isEmpty();
    }

    public String getAddressString() {
        StringBuilder sb = new StringBuilder();
        sb.append(zipCode).append(DELIMITER);
        sb.append(country).append(DELIMITER);
        sb.append(getCity().getFullAddressString()).append(DELIMITER);

        if (isPostOfficeBox) {
            sb.append("а/я").append(postOfficeBox);
        } else {
            sb.append(street.getFormalName()).append(DELIMITER);
            sb.append(house.getHouseNum());
            if (!Str.empty(apartments)) {
                sb.append(DELIMITER).append("кв. ").append(apartments);
            }
        }
        return sb.toString();
    }

    public void selectRegion(IRegion region) {
//		log.entry(city);
        this.region = region;
        regionSugessionList = null;
        regionNamePrefix = region.getFormalName();
        regionName = region.getRegionCode() + "";
    }

    public boolean isRegionSelected() {
        return region != null;
    }

    public void unselectRegion() {
//		log.entry();
        unselectCity();
        region = null;
        regionNamePrefix = null;
        regionName = null;
        regionSugessionList = null;
    }

    public List<Region> getRegionSugessions() {
//		log.entry(cityNamePrefix);

        if (isRegionSelected()) {
            return Collections.emptyList();
        }

        if (Str.empty(regionNamePrefix) || regionNamePrefix.length() < 3) {
            return Collections.emptyList();
        }

        regionSugessionList = addressFinder.findRegion(regionNamePrefix);
        log.exit(regionSugessionList.size());
        return regionSugessionList;
    }

    public void selectCity(ICity city) {
//		log.entry(city);
        this.city = city;
        citySugessionList = null;
        cityNamePrefix = city.getFormalName();
        regionName = city.getRegionCode() + "";
    }

    public boolean isCitySelected() {
        return city != null;
    }

    public void unselectCity() {
//		log.entry();
        unselectStreet();
        city = null;
        cityNamePrefix = null;
        regionName = null;
        citySugessionList = null;
    }

    public List<City> getCitySugessions() {
//		log.entry(cityNamePrefix);

        if (isCitySelected()) {
            return Collections.emptyList();
        }

        if (Str.empty(cityNamePrefix) || cityNamePrefix.length() < 3) {
            return Collections.emptyList();
        }

        citySugessionList = addressFinder.findCity(cityNamePrefix, isRegionSelected() ? region.getRegionCode() : null);
        log.exit(citySugessionList.size());
        return citySugessionList;
    }

    public void selectStreet(IStreet street) {
        this.street = street;
        streetSugessionList = null;
        streetNamePrefix = street.getFormalName();
    }

    public boolean isStreetSelected() {
        return street != null;
    }

    public void unselectStreet() {
        log.entry();
        unselectHouse();
        street = null;
        streetNamePrefix = null;
        streetSugessionList = null;
    }

    public List<Street> getStreetSugessions() {
//		log.entry(streetNamePrefix);

        if (isStreetSelected()) {
            return Collections.emptyList();
        }

        if (isPostOfficeBox) {
            return Collections.emptyList();
        }

        if (city == null || Str.empty(streetNamePrefix) || streetNamePrefix.length() < 3) {
            return Collections.emptyList();
        }

        streetSugessionList = addressFinder.findStreet(streetNamePrefix, city.getAoGuid());
        log.exit(streetSugessionList.size());
        return streetSugessionList;
    }

    public void selectHouse(IHouse house) {
        this.house = house;
        houseSugessionList = null;
        houseNamePrefix = house.getHouseNum();
        zipCode = house.getPostalCode();
    }

    public boolean isHouseSelected() {
        return house != null;
    }

    public void unselectHouse() {
        house = null;
        houseNamePrefix = null;
        apartments = null;
        zipCode = null;
        houseSugessionList = null;
    }

    public List<House> getHouseSugessions() {
        if (isHouseSelected()) {
            return Collections.emptyList();
        }

        if (isPostOfficeBox) {
            return Collections.emptyList();
        }

        if (city == null || street == null || Str.empty(houseNamePrefix)) {
            return Collections.emptyList();
        }

        houseSugessionList = addressFinder.findHouse(houseNamePrefix, street.getAoGuid());
        log.exit(houseSugessionList.size());
        return houseSugessionList;
    }

    public String getCountryName() {
        return country;
    }

    public void setCountryName(String country) {
        this.country = country;
    }

    public String getCityNamePrefix() {
        return cityNamePrefix;
    }

    public void setCityNamePrefix(String cityNamePrefix) {
        this.cityNamePrefix = cityNamePrefix;
        getCitySugessions();
    }

    public String getStreetNamePrefix() {
        return streetNamePrefix;
    }

    public void setStreetNamePrefix(String streetNamePrefix) {
        this.streetNamePrefix = streetNamePrefix;
        getStreetSugessions();
    }

    public String getCountry() {
        return country;
    }

    public String getRegionName() {
        return regionName;
    }

    public IRegion getRegion() {
        return region;
    }

    @NotNull
    public ICity getCity() {
        return city;
    }

    public IStreet getStreet() {
        return street;
    }

    public IHouse getHouse() {
        return house;
    }

    public String getHouseNamePrefix() {
        return houseNamePrefix;
    }

    public void setHouseNamePrefix(String houseNamePrefix) {
        this.houseNamePrefix = houseNamePrefix;
        getHouseSugessions();
    }

    private void cleanForm() {
        region = null;
        city = null;
        street = null;
        house = null;

        regionNamePrefix = null;
        cityNamePrefix = null;
        streetNamePrefix = null;
        houseNamePrefix = null;

        regionSugessionList = null;
        citySugessionList = null;
        streetSugessionList = null;
        houseSugessionList = null;
    }

    public void save() {
        log.entry();
        if (validate()) {
            listener.saveAddress(getAddressString());
        }
        cleanForm();
    }

    public void cancel() {
        log.entry();
        listener.cancel();;
        cleanForm();
    }

    @Size(min = 6, max = 6)
    @NotBlank
    public String getZipCode() {
        return zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public boolean isIsPostOfficeBox() {
        return isPostOfficeBox;
    }

    public void setIsPostOfficeBox(boolean isPostOfficeBox) {
        this.isPostOfficeBox = isPostOfficeBox;
    }

    public String getApartments() {
        return apartments;
    }

    public void setApartments(String apartments) {
        this.apartments = apartments;
    }

    public void isPostOfficeBoxChanged() {
        log.entry();
        unselectStreet();
    }

    public String getPostOfficeBox() {
        return postOfficeBox;
    }

directory-war/src/main/webapp/secure/common/kladrAddress.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" 
				xmlns:h="http://java.sun.com/jsf/html" 
				xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets" 
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:rich="http://richfaces.org/rich">


<style type="text/css">
	.change-selected-link{
		margin-left: 5px;
	}
</style>
	<a4j:outputPanel id="kladr_region_#{id}" ajaxRendered="true">
		<rich:panel style="width: 100%">
			<h:panelGrid id="kladr_edit_grid_#{id}" columns="1" style="width: 100%"
			columnClasses="filter-rows,filter-rows,filter-rows,filter-rows,filter-rows,filter-rows">
				<h:panelGroup>
					Данные из справочника КЛАДР

					<a4j:status id="sugessions_#{id}" >
						<f:facet name="start">
							<h:graphicImage value="/images/ai.gif" alt="ai" />
						</f:facet>
					</a4j:status>
				</h:panelGroup>
				<h:panelGroup />

				<h:panelGroup class="input-group input-group-sm">
					<h:outputLabel id="label_isPostOfficeBox_#{id}" for="isPostOfficeBox_field_#{id}" styleClass="input-group-addon single-column-directory-label" value="Абонентский ящик?" />
					<h:selectBooleanCheckbox id="isPostOfficeBox_field_#{id}" value="#{addressHelperBean.isPostOfficeBox}" styleClass="form-control"
						>
					<a4j:ajax event="change" execute="@this" render="kladr_edit_grid_#{id}"
							listener="#{addressHelperBean.isPostOfficeBoxChanged}"/>
					</h:selectBooleanCheckbox>
				</h:panelGroup>

				<h:panelGroup class="input-group input-group-sm">
					<h:outputLabel id="label_zipCode_#{id}" for="zipCode_field_#{id}" styleClass="input-group-addon single-column-directory-label" value="Индекс:" />
					<h:inputText id="zipCode_field_#{id}"  styleClass="form-control"
						value="#{addressHelperBean.zipCode}"
						maxlength="6"
						readonly="#{not addressHelperBean.isPostOfficeBox}"/>
				</h:panelGroup>

				<h:panelGroup class="input-group input-group-sm">
					<h:outputLabel id="label_country_#{id}" for="country_field_#{id}" styleClass="input-group-addon single-column-directory-label" value="Страна:" />
					<h:inputText id="country_field_#{id}"  styleClass="form-control"
					value="#{addressHelperBean.countryName}" readonly="true"/>
				</h:panelGroup>

				<!--<h:panelGroup class="input-group input-group-sm" rendered="{not addressHelperBean.isPostOfficeBox}">-->
					<!--<h:outputLabel id="label_region_{id}" for="region_field_{id}" styleClass="input-group-addon single-column-directory-label" value="Регион:" />-->
					<!--<h:inputText id="region_field_{id}"  styleClass="form-control"-->
						<!--value="{addressHelperBean.regionName}" readonly="true" />-->
				<!--</h:panelGroup>-->

				<!-- REGION -->


				<h:panelGroup class="input-group input-group-sm">
					<h:outputLabel id="label_region_#{id}" for="region_field_#{id}" styleClass="input-group-addon single-column-directory-label" value="Регион:" />
					<h:inputText id="region_field_#{id}" value="#{addressHelperBean.regionNamePrefix}"
						styleClass="form-control"
						rendered="#{not addressHelperBean.regionSelected}">
						<a4j:ajax event="keyup" render="region_sugession_panel_#{id}" limitRender="true"/>
					</h:inputText>
					<h:outputText value="#{addressHelperBean.region.formalName} #{addressHelperBean.region.shortName}"  rendered="#{addressHelperBean.regionSelected}"/>
					<a4j:commandLink action="#{addressHelperBean.unselectRegion}"
						rendered="#{addressHelperBean.regionSelected}"
	       			 	execute="@this" render="kladr_edit_grid_#{id}"
						styleClass="change-selected-link">
						<h:graphicImage value="/images/cross.png" alt="Изменить"
						width="20" height="20" title="Изменить"/>
					</a4j:commandLink>
				</h:panelGroup>


				<h:panelGroup id="region_sugession_panel_#{id}" class="input-group input-group-sm" rendered="#{not(addressHelperBean.regionSelected)}">
					<a4j:repeat value="#{addressHelperBean.regionSugessionList}"  var="region">
						<a4j:commandLink value="#{region.formalName} #{region.shortName}"
							action="#{addressHelperBean.selectRegion(region)}"
							execute="kladr_edit_grid_#{id}" render="kladr_edit_grid_#{id}"
						/>
						<br />

					</a4j:repeat>
				</h:panelGroup>

				<!-- CITY -->


				<h:panelGroup class="input-group input-group-sm">
					<h:outputLabel id="label_city_#{id}" for="city_field_#{id}" styleClass="input-group-addon single-column-directory-label" value="Город:" />
					<h:inputText id="city_field_#{id}" value="#{addressHelperBean.cityNamePrefix}"
						styleClass="form-control"
						rendered="#{not addressHelperBean.citySelected}">
						<a4j:ajax event="keyup" render="city_sugession_panel_#{id}" limitRender="true"/>
					</h:inputText>
					<h:outputText value="#{addressHelperBean.city.formalName}"  rendered="#{addressHelperBean.citySelected}"/>
					<a4j:commandLink action="#{addressHelperBean.unselectCity}"
						rendered="#{addressHelperBean.citySelected}"
	       			 	execute="@this" render="kladr_edit_grid_#{id}"
						styleClass="change-selected-link">
						<h:graphicImage value="/images/cross.png" alt="Изменить"
						width="20" height="20" title="Изменить"/>
					</a4j:commandLink>
				</h:panelGroup>


				<h:panelGroup id="city_sugession_panel_#{id}" class="input-group input-group-sm" rendered="#{not(addressHelperBean.citySelected)}">
					<a4j:repeat value="#{addressHelperBean.citySugessionList}"  var="c">
						<a4j:commandLink value="#{c.shortName}. #{c.formalName} (#{c.fullAddressString})"
							action="#{addressHelperBean.selectCity(c)}"
							execute="kladr_edit_grid_#{id}" render="kladr_edit_grid_#{id}"
						/>
						<br />

					</a4j:repeat>
				</h:panelGroup>

				<!-- STREET -->
				<h:panelGroup class="input-group input-group-sm" rendered="#{addressHelperBean.citySelected and not addressHelperBean.isPostOfficeBox}">
					<h:outputLabel id="label_street_#{id}" for="street_field_#{id}" styleClass="input-group-addon single-column-directory-label" value="Улица:" />
					<h:inputText id="street_field_#{id}" value="#{addressHelperBean.streetNamePrefix}"
						styleClass="form-control"
						rendered="#{not addressHelperBean.streetSelected}">
						<a4j:ajax event="keyup" render="street_sugession_panel_#{id}" limitRender="true"/>
					</h:inputText>
					<h:outputText value="#{addressHelperBean.street.formalName}"  rendered="#{addressHelperBean.streetSelected}"/>
					<a4j:commandLink action="#{addressHelperBean.unselectStreet}"
						rendered="#{addressHelperBean.streetSelected}"
						execute="@this" render="kladr_edit_grid_#{id}, @region"
						styleClass="change-selected-link">
						<h:graphicImage value="/images/cross.png" alt="Изменить"
						width="20" height="20" title="Изменить"/>
					</a4j:commandLink>
				</h:panelGroup>


				<h:panelGroup id="street_sugession_panel_#{id}" class="input-group input-group-sm" rendered="#{not addressHelperBean.streetSelected}" >
					<a4j:repeat value="#{addressHelperBean.streetSugessionList}"  var="c">
						<a4j:commandLink value="#{c.formalName}"
							action="#{addressHelperBean.selectStreet(c)}"
							execute="kladr_edit_grid_#{id}" render="kladr_edit_grid_#{id}"
						/>
						<br />

					</a4j:repeat>
				</h:panelGroup>


				<!-- HOUSE -->
				<h:panelGroup class="input-group input-group-sm" rendered="#{addressHelperBean.streetSelected and not addressHelperBean.isPostOfficeBox}">
					<h:outputLabel id="label_house_#{id}" for="house_field_#{id}" styleClass="input-group-addon single-column-directory-label" value="Дом:" />
					<h:inputText id="house_field_#{id}" value="#{addressHelperBean.houseNamePrefix}"
						styleClass="form-control"
						rendered="#{not addressHelperBean.houseSelected}">
						<a4j:ajax event="keyup" render="house_sugession_panel_#{id}" limitRender="true"/>
					</h:inputText>
					<h:outputText value="#{addressHelperBean.house.houseNum}"  rendered="#{addressHelperBean.houseSelected}"/>
					<a4j:commandLink action="#{addressHelperBean.unselectHouse}"
						rendered="#{addressHelperBean.houseSelected}"
						execute="kladr_edit_grid_#{id}" render="kladr_edit_grid_#{id}, @region"
						styleClass="change-selected-link">
						<h:graphicImage value="/images/cross.png" alt="Изменить"
							width="20" height="20" title="Изменить"/>
					</a4j:commandLink>
				</h:panelGroup>


				<h:panelGroup id="house_sugession_panel_#{id}" class="input-group input-group-sm" rendered="#{not addressHelperBean.houseSelected}" >
					<a4j:repeat value="#{addressHelperBean.houseSugessionList}"  var="h">
						<a4j:commandLink value="#{h.houseNum} #{h.houseId == null ? '(для дома отсутствует запись в БД)' : ''}"
							action="#{addressHelperBean.selectHouse(h)}"
							execute="kladr_edit_grid_#{id}" render="kladr_edit_grid_#{id}, @region"
						/>
						<br />

					</a4j:repeat>
				</h:panelGroup>

				<!-- zipCode -->
				<h:panelGroup class="input-group input-group-sm" rendered="#{addressHelperBean.houseSelected and addressHelperBean.house.houseId == null}">
					<h:outputLabel id="label_zipcode_#{id}" for="zipcode_field_#{id}" styleClass="input-group-addon single-column-directory-label" value="Индекс:" />
					<h:inputText id="zipcode_field_#{id}" value="#{addressHelperBean.zipCode}"
						styleClass="form-control" required="true" requiredMessage="Выбранный дом не найден в базе данных, необходимо указать почтовый индекс"/>
				</h:panelGroup>

				<!-- Apartment -->
				<h:panelGroup class="input-group input-group-sm" rendered="#{addressHelperBean.houseSelected and not addressHelperBean.isPostOfficeBox}">
					<h:outputLabel id="label_apartments_#{id}" for="apartments_field_#{id}" styleClass="input-group-addon single-column-directory-label" value="Квартира:" />
					<h:inputText id="apartments_field_#{id}" value="#{addressHelperBean.apartments}"
						styleClass="form-control" />
				</h:panelGroup>

				<!-- Абонентский ящик -->
				<h:panelGroup class="input-group input-group-sm" rendered="#{addressHelperBean.isPostOfficeBox}">
					<h:outputLabel id="label_postalOfficeBox_#{id}" for="postalOfficeBox_field_#{id}" styleClass="input-group-addon single-column-directory-label" value="Номер абонентсккого ящика:" />
					<h:inputText id="postalOfficeBox_field_#{id}" value="#{addressHelperBean.postOfficeBox}"
						styleClass="form-control" />
				</h:panelGroup>

				<h:panelGroup >
					<div id="add_buttons_wrapper" class="buttons-wrapper">
						<a4j:commandLink value="Сохранить" styleClass="filter-button btn btn-primary"
							rendered="#{addressHelperBean.streetSelected or addressHelperBean.isPostOfficeBox}"
							action="#{addressHelperBean.save}"
							execute="kladr_edit_grid_#{id}" render="@form" />
						<a4j:commandLink value="Отмена" styleClass="filter-button btn btn-primary"
							action="#{addressHelperBean.cancel}"
							execute="@this" render="@form"/>
					</div>
				</h:panelGroup>
			</h:panelGrid>
		</rich:panel>
	</a4j:outputPanel>
</ui:composition>

directory-war/src/main/webapp/secure/common/menuBar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:a4j="http://richfaces.org/a4j"
                xmlns:rich="http://richfaces.org/rich">
    <nav id="main_menu_bar" class="navbar navbar-default" role="navigation">
        <div id="main_menu_container" class="container-fluid">
            <div class="collapse navbar-collapse" id="main_menu_collapse">
                <ul id="menu_list" class="nav navbar-nav navbar-left">
                    <li id="directories_list" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><h4>Справочники<span class="caret"></span></h4></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="/directory/secure/juridicals/list.xhtml">Контрагенты</a></li>
							<li><hr/></li>

                            <li><a href="/directory/secure/ageBrackets/list.xhtml">Возрастные группы</a></li>

                            <li><a href="/directory/secure/stay/list.xhtml">Режимы пребывания</a></li>

                            <li><a href="/directory/secure/productCategories/list.xhtml">Категории продуктов</a></li>

                            <li><a href="/directory/secure/normGroups/list.xhtml">Группы норм</a></li>
                            <li><hr/></li>

                            <li><a href="/directory/secure/product/trademark/list.xhtml">Торговые марки</a></li>
                            <li><a href="/directory/secure/product/product/list.xhtml">Продукты</a></li>
                            <li><a href="/directory/secure/product/productimage/list.xhtml">Образы</a></li>
                            <li><a href="/directory/secure/product/packingFlowChart/list.xhtml">Технологические карты</a></li>
							<li><hr/></li>
							<li><a href="/directory/secure/measure/list.xhtml">Единицы измерения</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</ui:composition>

directory-war/src/main/webapp/secure/common/messages.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:a4j="http://richfaces.org/a4j"
                xmlns:rich="http://richfaces.org/rich">
	<a4j:outputPanel id="messages_panel" ajaxRendered="true">
		<h:form id="messages_form" rendered="#{!empty facesContext.maximumSeverity}">
			<h:panelGroup id="messages_wrapper" layout="block"
						styleClass="well">
				<rich:messages id="main_messages" styleClass="messages"/>
			</h:panelGroup>
		</h:form>
	</a4j:outputPanel>
</ui:composition>